trigger: none

pool:
  vmImage: 'Ubuntu-latest'

steps:

- script: |
    echo "Build Details"
    echo "Build Id: $(Build.BuildId)"
    echo "Build Number: $(Build.BuildNumber)"
    echo "Build Definition Name: $(Build.DefinitionName)"
    echo "Build Repository: $(Build.Repository.Name)"
    echo "Build Repository Provider: $(Build.Repository.Provider)"
    echo "Building on Branch: $(Build.SourceBranch)"
    echo "Build Commit Number: $(Build.SourceVersion)"
    echo "Release Details"
    echo "Release Id: $(Release.ReleaseId)"
    echo "Release Number: $(Release.ReleaseNumber)"
    echo "Release Environment: $(Release.EnvironmentName)"
    echo "Release Requested By: $(Release.Deployment.Requestedfor)"
    echo "Agent Details"
    echo "Agent Id: $(Agent.AgentId)"
    echo "Agent Name: $(Agent.Name)"
    echo "Agent OS: $(Agent.OS)"
    echo "Agent Version: $(Agent.Version)"
    echo "System details"
    echo "Project Name: $(System.TeamProjectName)"
    echo "Default Working Directory: $(System.DefaultWorkingDirectory)"
    echo "Stage Name: $(System.StageName)"
    echo "Stage Display Name: $(System.StageDisplayName)"
    echo "Job Name: $(System.JobName)"
    echo "Job Display Name: $(System.JobDisplayName)"
    
  displayName: 'Print Predefined Variables'
