trigger: none

pool:
  name: Default

steps:

- script: |
    echo "Building on branch $(Build.SourceBranch)"
    echo "Current build number: $(Build.BuildNumber)"
    echo "Definition name: $(Build.DefinitionName)"
  displayName: 'Print Predefined Variables'
