trigger: none

pool:
  vmImage: 'Ubuntu-latest'

steps:

- script: |
    echo "Build Details"
    echo "Build Id: $(Build.Id)"
    echo "Build Number: $(Build.BuildNumber)"
    echo "Build Definition Name: $(Build.DefinitionName)"
    echo "Build Repository: $(Build.Repository.Name)"
    echo "Build Repository Provider: $(Build.Repository.Provider)"
    echo "Building on Branch: $(Build.SourceBranch)"
    echo "Build Commit Number: $(Build.SourceVersion)"
    echo "Definition name: $(Build.DefinitionName)"
  displayName: 'Print Predefined Variables'
