trigger: none

pool:
  name: Default

steps:

- script: |
    echo 'Build Id: $(Build.Id)'
    echo 'Build Number: $(Build.Number)'
    echo 'Build Definition Name: $(Build.Definition.Name)'
  displayName: 'Print Predefined Variables'
