trigger: none

pool:
  vmImage: 'Ubuntu-latest'

steps:

- script: |
    echo "Build Details"
    echo "Build Id: $(Build.BuildId)"
    echo "Build Number: $(Build.BuildNumber)"
    echo "Build Definition Name: $(Build.DefinitionName)"
    echo "Build Repository: $(Build.Repository.Name)"
    echo "Build Repository Provider: $(Build.Repository.Provider)"
    echo "Building on Branch: $(Build.SourceBranch)"
    echo "Build Commit Number: $(Build.SourceVersion)"
    echo "Release Details"
    echo "Release Id: $(Release.ReleaseId)"
    echo "Release Number: $(Release.ReleaseNumber)"
    echo "Release Name: $(Release.ReleaseName)"
    echo "Release Environment: $(Release.EnvironmentName)"
    echo "Release Definition Name: $(Release.DefinitionName)"
    echo "Release Requested By: $(Release.Deployment.RequestedFor)"
    echo "Agent Details"
    echo "Agent Name: $(Agent.Name)"
    echo "Agent OS: $(Agent.OS)"
    echo "Agent Version: $(Agent.Version)"
    echo "System details"
    echo "Project Name: $(System.TeamProjectName)"
    echo "Default Working Directory: $(System.DefaultWorkingDirectory)"
    echo "Stage Name: $(System.StageName)"
    echo "Stage Display Name: $(System.StageDisplayName)"
    echo "Job Name: $(System.JobName)"
    echo "Job Display Name: $(System.JobDisplayName)"
    echo "Is in Debug mode: $(System.Debug)"
    echo "Pull Request Source Branch : $(System.PullRequest.SourceBranch)"
    echo "Pull Request Target Branch : $(System.PullRequest.TargetBranch)"
    echo "Access Token : $(System.AccessToken)"
    echo "Artifacts Directory : $(System.ArtifactsDirectory)"
    echo "CollectionId : $(System.CollectionId)"

    
  displayName: 'Print Predefined Variables'
